//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projekat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string Adresa {
            get {
                return ResourceManager.GetString("Adresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bračno stanje.
        /// </summary>
        public static string BracnoStanje {
            get {
                return ResourceManager.GetString("BracnoStanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona.
        /// </summary>
        public static string BrojTelefona {
            get {
                return ResourceManager.GetString("BrojTelefona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Datum {
            get {
                return ResourceManager.GetString("Datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum izdavanja uputa.
        /// </summary>
        public static string DatumIzdavanjaUputa {
            get {
                return ResourceManager.GetString("DatumIzdavanjaUputa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj podsetnik.
        /// </summary>
        public static string DodajPodsetnik {
            get {
                return ResourceManager.GetString("DodajPodsetnik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronađite lekara po prezimenu, imenu ili specijalizaciji.
        /// </summary>
        public static string FilterLekari {
            get {
                return ResourceManager.GetString("FilterLekari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specijalistički pregled.
        /// </summary>
        public static string GboxSpecijalistickiPregled {
            get {
                return ResourceManager.GetString("GboxSpecijalistickiPregled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string Ime {
            get {
                return ResourceManager.GetString("Ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime pacijenta.
        /// </summary>
        public static string ImePacijenta {
            get {
                return ResourceManager.GetString("ImePacijenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *2. Izaberite datum.
        /// </summary>
        public static string IzaberiteDatum {
            get {
                return ResourceManager.GetString("IzaberiteDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promeni jezik.
        /// </summary>
        public static string IzaberiteJezik {
            get {
                return ResourceManager.GetString("IzaberiteJezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *4. Izaberite lekara.
        /// </summary>
        public static string IzaberiteLekara {
            get {
                return ResourceManager.GetString("IzaberiteLekara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *1. Izaberite tip termina.
        /// </summary>
        public static string IzaberiteTipTermina {
            get {
                return ResourceManager.GetString("IzaberiteTipTermina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *3. Izaberite vreme početka.
        /// </summary>
        public static string IzaberiteVremePocetka {
            get {
                return ResourceManager.GetString("IzaberiteVremePocetka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izabrani lekar.
        /// </summary>
        public static string IzabraniLekar {
            get {
                return ResourceManager.GetString("IzabraniLekar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promeni temu.
        /// </summary>
        public static string IzberiteTemu {
            get {
                return ResourceManager.GetString("IzberiteTemu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmenite podatke.
        /// </summary>
        public static string IzmenitePodatke {
            get {
                return ResourceManager.GetString("IzmenitePodatke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG .
        /// </summary>
        public static string JmbgPacijenta {
            get {
                return ResourceManager.GetString("JmbgPacijenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdravstveni karton.
        /// </summary>
        public static string Karton {
            get {
                return ResourceManager.GetString("Karton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        public static string KorisnickoIme {
            get {
                return ResourceManager.GetString("KorisnickoIme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekar kod kog se upućuje.
        /// </summary>
        public static string LekarKodKogSeUpucuje {
            get {
                return ResourceManager.GetString("LekarKodKogSeUpucuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekar.
        /// </summary>
        public static string LekarPodaci {
            get {
                return ResourceManager.GetString("LekarPodaci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime i prezime izabranog lekara.
        /// </summary>
        public static string LekarToolTip {
            get {
                return ResourceManager.GetString("LekarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string Lozinka {
            get {
                return ResourceManager.GetString("Lozinka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napomena.
        /// </summary>
        public static string Napomena {
            get {
                return ResourceManager.GetString("Napomena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekarski uput za specijalistički pregled.
        /// </summary>
        public static string NaslovUputa {
            get {
                return ResourceManager.GetString("NaslovUputa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔔 Obaveštenja.
        /// </summary>
        public static string Obavestenja {
            get {
                return ResourceManager.GetString("Obavestenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrisi selektovano obavestenje.
        /// </summary>
        public static string ObrisiObavestenje {
            get {
                return ResourceManager.GetString("ObrisiObavestenje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjavi se.
        /// </summary>
        public static string Odjava {
            get {
                return ResourceManager.GetString("Odjava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string Odustani {
            get {
                return ResourceManager.GetString("Odustani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijent.
        /// </summary>
        public static string PacijentPodaci {
            get {
                return ResourceManager.GetString("PacijentPodaci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početna stranica.
        /// </summary>
        public static string Pocetna {
            get {
                return ResourceManager.GetString("Pocetna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pol.
        /// </summary>
        public static string Pol {
            get {
                return ResourceManager.GetString("Pol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomeri.
        /// </summary>
        public static string Pomeri {
            get {
                return ResourceManager.GetString("Pomeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popuni anketu.
        /// </summary>
        public static string PopuniAnketu {
            get {
                return ResourceManager.GetString("PopuniAnketu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potpis.
        /// </summary>
        public static string PotpisLekara {
            get {
                return ResourceManager.GetString("PotpisLekara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string Potvrdi {
            get {
                return ResourceManager.GetString("Potvrdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled.
        /// </summary>
        public static string Pregled {
            get {
                return ResourceManager.GetString("Pregled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string Prezime {
            get {
                return ResourceManager.GetString("Prezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime pacijenta.
        /// </summary>
        public static string PrezimePacijenta {
            get {
                return ResourceManager.GetString("PrezimePacijenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaš profil.
        /// </summary>
        public static string Profil {
            get {
                return ResourceManager.GetString("Profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadržaj.
        /// </summary>
        public static string SadrzajObavestenja {
            get {
                return ResourceManager.GetString("SadrzajObavestenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specijalizacija.
        /// </summary>
        public static string Specijalizacija {
            get {
                return ResourceManager.GetString("Specijalizacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svetla.
        /// </summary>
        public static string Svetla {
            get {
                return ResourceManager.GetString("Svetla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamna.
        /// </summary>
        public static string Tamna {
            get {
                return ResourceManager.GetString("Tamna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        public static string TipObavestenja {
            get {
                return ResourceManager.GetString("TipObavestenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uvid u selektovano obavestenje.
        /// </summary>
        public static string UvidObavestenje {
            get {
                return ResourceManager.GetString("UvidObavestenje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uvid u zakazane termine.
        /// </summary>
        public static string UvidUZakazaneTermine {
            get {
                return ResourceManager.GetString("UvidUZakazaneTermine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakaži termin.
        /// </summary>
        public static string ZakaziTermin {
            get {
                return ResourceManager.GetString("ZakaziTermin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zanimanje.
        /// </summary>
        public static string Zanimanje {
            get {
                return ResourceManager.GetString("Zanimanje", resourceCulture);
            }
        }
    }
}
