//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projekat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string Adresa {
            get {
                return ResourceManager.GetString("Adresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anamneza.
        /// </summary>
        public static string Anamneza {
            get {
                return ResourceManager.GetString("Anamneza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o anamnezi.
        /// </summary>
        public static string AnamnezaPodaci {
            get {
                return ResourceManager.GetString("AnamnezaPodaci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anamneze.
        /// </summary>
        public static string Anamneze {
            get {
                return ResourceManager.GetString("Anamneze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anketa o radu lekara.
        /// </summary>
        public static string AnketaOLekaru {
            get {
                return ResourceManager.GetString("AnketaOLekaru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beleške.
        /// </summary>
        public static string Beleske {
            get {
                return ResourceManager.GetString("Beleske", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosna i Hercegovina.
        /// </summary>
        public static string Bosna {
            get {
                return ResourceManager.GetString("Bosna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bračno stanje.
        /// </summary>
        public static string BracnoStanje {
            get {
                return ResourceManager.GetString("BracnoStanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj kreveta.
        /// </summary>
        public static string brKreveta {
            get {
                return ResourceManager.GetString("brKreveta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koliko dana uzimati leka.
        /// </summary>
        public static string BrojDana {
            get {
                return ResourceManager.GetString("BrojDana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj dana.
        /// </summary>
        public static string BrojDana2 {
            get {
                return ResourceManager.GetString("BrojDana2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj kartice.
        /// </summary>
        public static string BrojKartice {
            get {
                return ResourceManager.GetString("BrojKartice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona.
        /// </summary>
        public static string BrojTelefona {
            get {
                return ResourceManager.GetString("BrojTelefona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj sobe.
        /// </summary>
        public static string brSobe {
            get {
                return ResourceManager.GetString("brSobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Kako biste ocenili stručnost zaposlenih u Zdravo korporaciji?.
        /// </summary>
        public static string Cetiri {
            get {
                return ResourceManager.GetString("Cetiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Kako biste ocenili stručnost lekara u radu na racunaru?.
        /// </summary>
        public static string Cetvrto {
            get {
                return ResourceManager.GetString("Cetvrto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da.
        /// </summary>
        public static string Da {
            get {
                return ResourceManager.GetString("Da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Datum {
            get {
                return ResourceManager.GetString("Datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum izdavanja uputa.
        /// </summary>
        public static string DatumIzdavanjaUputa {
            get {
                return ResourceManager.GetString("DatumIzdavanjaUputa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum kraja lečenja.
        /// </summary>
        public static string DatumKrajaLecenja {
            get {
                return ResourceManager.GetString("DatumKrajaLecenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum početka lečenja.
        /// </summary>
        public static string DatumPocetkaLecenja {
            get {
                return ResourceManager.GetString("DatumPocetkaLecenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum propisivanja leka.
        /// </summary>
        public static string DatumPropisivanja {
            get {
                return ResourceManager.GetString("DatumPropisivanja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum važenja.
        /// </summary>
        public static string DatumVazenja {
            get {
                return ResourceManager.GetString("DatumVazenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dnevno uzimanje leka.
        /// </summary>
        public static string DnevnoUzimanje {
            get {
                return ResourceManager.GetString("DnevnoUzimanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string Dodaj {
            get {
                return ResourceManager.GetString("Dodaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj podsetnik.
        /// </summary>
        public static string DodajPodsetnik {
            get {
                return ResourceManager.GetString("DodajPodsetnik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite drugog lekara.
        /// </summary>
        public static string DrugiLekar {
            get {
                return ResourceManager.GetString("DrugiLekar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Kako biste ocenili odnos lekara prema pacijentima i drugim zaposlenima?.
        /// </summary>
        public static string Drugo {
            get {
                return ResourceManager.GetString("Drugo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država.
        /// </summary>
        public static string Drzava {
            get {
                return ResourceManager.GetString("Drzava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Kako biste ocenili efikasnost online zakazivanja, pomeranja i otkazivanja termina?.
        /// </summary>
        public static string Dva {
            get {
                return ResourceManager.GetString("Dva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektronsko placanje.
        /// </summary>
        public static string ElektronskoPlacanje {
            get {
                return ResourceManager.GetString("ElektronskoPlacanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronađite lekara po prezimenu, imenu ili specijalizaciji.
        /// </summary>
        public static string FilterLekari {
            get {
                return ResourceManager.GetString("FilterLekari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specijalistički pregled.
        /// </summary>
        public static string GboxSpecijalistickiPregled {
            get {
                return ResourceManager.GetString("GboxSpecijalistickiPregled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina.
        /// </summary>
        public static string Godina {
            get {
                return ResourceManager.GetString("Godina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad.
        /// </summary>
        public static string Grad {
            get {
                return ResourceManager.GetString("Grad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrvatska.
        /// </summary>
        public static string Hrvatska {
            get {
                return ResourceManager.GetString("Hrvatska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string Ime {
            get {
                return ResourceManager.GetString("Ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime i prezime na kartici.
        /// </summary>
        public static string ImeIPrezimeNaKartici {
            get {
                return ResourceManager.GetString("ImeIPrezimeNaKartici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime pacijenta.
        /// </summary>
        public static string ImePacijenta {
            get {
                return ResourceManager.GetString("ImePacijenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *2. Izaberite datum.
        /// </summary>
        public static string IzaberiteDatum {
            get {
                return ResourceManager.GetString("IzaberiteDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite jednu od ponuđenih preferenci.
        /// </summary>
        public static string IzaberiteJednu {
            get {
                return ResourceManager.GetString("IzaberiteJednu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promeni jezik.
        /// </summary>
        public static string IzaberiteJezik {
            get {
                return ResourceManager.GetString("IzaberiteJezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *4. Izaberite lekara.
        /// </summary>
        public static string IzaberiteLekara {
            get {
                return ResourceManager.GetString("IzaberiteLekara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite lekara.
        /// </summary>
        public static string IzaberiteLekara2 {
            get {
                return ResourceManager.GetString("IzaberiteLekara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *1. Izaberite tip termina.
        /// </summary>
        public static string IzaberiteTipTermina {
            get {
                return ResourceManager.GetString("IzaberiteTipTermina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *1.1. Izaberite uput.
        /// </summary>
        public static string IzaberiteUput {
            get {
                return ResourceManager.GetString("IzaberiteUput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *3. Izaberite vreme početka.
        /// </summary>
        public static string IzaberiteVremePocetka {
            get {
                return ResourceManager.GetString("IzaberiteVremePocetka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izabrani lekar.
        /// </summary>
        public static string IzabraniLekar {
            get {
                return ResourceManager.GetString("IzabraniLekar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promeni temu.
        /// </summary>
        public static string IzberiteTemu {
            get {
                return ResourceManager.GetString("IzberiteTemu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni.
        /// </summary>
        public static string Izmeni {
            get {
                return ResourceManager.GetString("Izmeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmenite podatke.
        /// </summary>
        public static string IzmenitePodatke {
            get {
                return ResourceManager.GetString("IzmenitePodatke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izveštaj.
        /// </summary>
        public static string Izvestaj {
            get {
                return ResourceManager.GetString("Izvestaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Kako biste ocenili kvalitet usluga koje Vam nudi Zdravo korporacija?.
        /// </summary>
        public static string Jedan {
            get {
                return ResourceManager.GetString("Jedan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG pacijenta.
        /// </summary>
        public static string JmbgPacijenta {
            get {
                return ResourceManager.GetString("JmbgPacijenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kakav pregled se traži.
        /// </summary>
        public static string KakavPregledSeTrazi {
            get {
                return ResourceManager.GetString("KakavPregledSeTrazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdravstveni karton.
        /// </summary>
        public static string Karton {
            get {
                return ResourceManager.GetString("Karton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        public static string KorisnickoIme {
            get {
                return ResourceManager.GetString("KorisnickoIme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite datum i odaberite jedan od preporucenih termina.
        /// </summary>
        public static string lblPodnaslov {
            get {
                return ResourceManager.GetString("lblPodnaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📆 Preporučeni termini.
        /// </summary>
        public static string LblPreporuceniTermini {
            get {
                return ResourceManager.GetString("LblPreporuceniTermini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekar.
        /// </summary>
        public static string Lekar {
            get {
                return ResourceManager.GetString("Lekar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekar kod kog se upućuje.
        /// </summary>
        public static string LekarKodKogSeUpucuje {
            get {
                return ResourceManager.GetString("LekarKodKogSeUpucuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekar.
        /// </summary>
        public static string LekarPodaci {
            get {
                return ResourceManager.GetString("LekarPodaci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekarski recept.
        /// </summary>
        public static string LekarskiRecept {
            get {
                return ResourceManager.GetString("LekarskiRecept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekarski recepti.
        /// </summary>
        public static string LekarskiRecepti {
            get {
                return ResourceManager.GetString("LekarskiRecepti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekarski uputi.
        /// </summary>
        public static string LekarskiUputi {
            get {
                return ResourceManager.GetString("LekarskiUputi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime i prezime izabranog lekara.
        /// </summary>
        public static string LekarToolTip {
            get {
                return ResourceManager.GetString("LekarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string Lozinka {
            get {
                return ResourceManager.GetString("Lozinka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesec.
        /// </summary>
        public static string Mesec {
            get {
                return ResourceManager.GetString("Mesec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifikuj termine.
        /// </summary>
        public static string Modifikacija {
            get {
                return ResourceManager.GetString("Modifikacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muški.
        /// </summary>
        public static string Muski {
            get {
                return ResourceManager.GetString("Muski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napomena.
        /// </summary>
        public static string Napomena {
            get {
                return ResourceManager.GetString("Napomena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anketa o uslugama Zdravo korporacije.
        /// </summary>
        public static string NaslovAnketaKlinika {
            get {
                return ResourceManager.GetString("NaslovAnketaKlinika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratorijski uput.
        /// </summary>
        public static string NaslovLabrUputa {
            get {
                return ResourceManager.GetString("NaslovLabrUputa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekarski uput za specijalistički pregled.
        /// </summary>
        public static string NaslovUputa {
            get {
                return ResourceManager.GetString("NaslovUputa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazad.
        /// </summary>
        public static string Nazad {
            get {
                return ResourceManager.GetString("Nazad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv ankete.
        /// </summary>
        public static string NazivAnkete {
            get {
                return ResourceManager.GetString("NazivAnkete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv leka.
        /// </summary>
        public static string NazivLeka {
            get {
                return ResourceManager.GetString("NazivLeka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        public static string Ne {
            get {
                return ResourceManager.GetString("Ne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neoženjen/Neudata.
        /// </summary>
        public static string Neozenjen {
            get {
                return ResourceManager.GetString("Neozenjen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novi podsetnik.
        /// </summary>
        public static string NoviPodsetnik {
            get {
                return ResourceManager.GetString("NoviPodsetnik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔔 Obaveštenja.
        /// </summary>
        public static string Obavestenja {
            get {
                return ResourceManager.GetString("Obavestenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrisi selektovano obavestenje.
        /// </summary>
        public static string ObrisiObavestenje {
            get {
                return ResourceManager.GetString("ObrisiObavestenje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1️⃣-veoma lose, 2️⃣-lose, 3️⃣-dobro, 4️⃣-vrlo dobro, 5️⃣-odlicno.
        /// </summary>
        public static string Ocene {
            get {
                return ResourceManager.GetString("Ocene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjavi se.
        /// </summary>
        public static string Odjava {
            get {
                return ResourceManager.GetString("Odjava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string Odustani {
            get {
                return ResourceManager.GetString("Odustani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis bolesti.
        /// </summary>
        public static string OpisBolesti {
            get {
                return ResourceManager.GetString("OpisBolesti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis uputa.
        /// </summary>
        public static string OpisUputa {
            get {
                return ResourceManager.GetString("OpisUputa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkaži termin.
        /// </summary>
        public static string OtkaziTermin {
            get {
                return ResourceManager.GetString("OtkaziTermin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oženjen/Udata.
        /// </summary>
        public static string Ozenjen {
            get {
                return ResourceManager.GetString("Ozenjen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijent.
        /// </summary>
        public static string Pacijent {
            get {
                return ResourceManager.GetString("Pacijent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijent.
        /// </summary>
        public static string PacijentPodaci {
            get {
                return ResourceManager.GetString("PacijentPodaci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Kako biste ocenili higijenu u klinikama Zdravo korporacije?.
        /// </summary>
        public static string Pet {
            get {
                return ResourceManager.GetString("Pet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početak terapije.
        /// </summary>
        public static string PocetakTerapije {
            get {
                return ResourceManager.GetString("PocetakTerapije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početna stranica.
        /// </summary>
        public static string Pocetna {
            get {
                return ResourceManager.GetString("Pocetna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏰ Podsetnici.
        /// </summary>
        public static string Podsetnici {
            get {
                return ResourceManager.GetString("Podsetnici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pol.
        /// </summary>
        public static string Pol {
            get {
                return ResourceManager.GetString("Pol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomeri.
        /// </summary>
        public static string Pomeri {
            get {
                return ResourceManager.GetString("Pomeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomeri termin.
        /// </summary>
        public static string PomeriTermin {
            get {
                return ResourceManager.GetString("PomeriTermin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popuni.
        /// </summary>
        public static string Popuni {
            get {
                return ResourceManager.GetString("Popuni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popuni anketu.
        /// </summary>
        public static string PopuniAnketu {
            get {
                return ResourceManager.GetString("PopuniAnketu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poštanski broj.
        /// </summary>
        public static string PostanskiBroj {
            get {
                return ResourceManager.GetString("PostanskiBroj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potpis lekara.
        /// </summary>
        public static string PotpisLekara {
            get {
                return ResourceManager.GetString("PotpisLekara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string Potvrdi {
            get {
                return ResourceManager.GetString("Potvrdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        public static string Preference {
            get {
                return ResourceManager.GetString("Preference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled.
        /// </summary>
        public static string Pregled {
            get {
                return ResourceManager.GetString("Pregled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preporučeni termini.
        /// </summary>
        public static string PreporuceniTermini {
            get {
                return ResourceManager.GetString("PreporuceniTermini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string Prezime {
            get {
                return ResourceManager.GetString("Prezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime pacijenta.
        /// </summary>
        public static string PrezimePacijenta {
            get {
                return ResourceManager.GetString("PrezimePacijenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavi se.
        /// </summary>
        public static string PrijaviSe {
            get {
                return ResourceManager.GetString("PrijaviSe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaš profil.
        /// </summary>
        public static string Profil {
            get {
                return ResourceManager.GetString("Profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronađite lekara.
        /// </summary>
        public static string PronadjiteLekara {
            get {
                return ResourceManager.GetString("PronadjiteLekara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Kako biste ocenili strucnost lekara u svom radu?.
        /// </summary>
        public static string Prvo {
            get {
                return ResourceManager.GetString("Prvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razveden/Razvedena.
        /// </summary>
        public static string Razveden {
            get {
                return ResourceManager.GetString("Razveden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recept.
        /// </summary>
        public static string Recept {
            get {
                return ResourceManager.GetString("Recept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj.
        /// </summary>
        public static string Sacuvaj {
            get {
                return ResourceManager.GetString("Sacuvaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadržaj.
        /// </summary>
        public static string SadrzajObavestenja {
            get {
                return ResourceManager.GetString("SadrzajObavestenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala.
        /// </summary>
        public static string Sala {
            get {
                return ResourceManager.GetString("Sala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenija.
        /// </summary>
        public static string Slovenija {
            get {
                return ResourceManager.GetString("Slovenija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specijalistički pregled.
        /// </summary>
        public static string SpecijalistickiPregled {
            get {
                return ResourceManager.GetString("SpecijalistickiPregled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specijalizacija.
        /// </summary>
        public static string Specijalizacija {
            get {
                return ResourceManager.GetString("Specijalizacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srbija.
        /// </summary>
        public static string Srbija {
            get {
                return ResourceManager.GetString("Srbija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svetla.
        /// </summary>
        public static string Svetla {
            get {
                return ResourceManager.GetString("Svetla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamna.
        /// </summary>
        public static string Tamna {
            get {
                return ResourceManager.GetString("Tamna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronađite termin po datumu (MM/dd/yyyy).
        /// </summary>
        public static string TekstLabeleZaPretragu {
            get {
                return ResourceManager.GetString("TekstLabeleZaPretragu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        public static string Tema {
            get {
                return ResourceManager.GetString("Tema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terapija.
        /// </summary>
        public static string Terapija {
            get {
                return ResourceManager.GetString("Terapija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o terminu.
        /// </summary>
        public static string TerminPodaci {
            get {
                return ResourceManager.GetString("TerminPodaci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        public static string TipObavestenja {
            get {
                return ResourceManager.GetString("TipObavestenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip termina.
        /// </summary>
        public static string TipTermin {
            get {
                return ResourceManager.GetString("TipTermin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip termina.
        /// </summary>
        public static string TipTermina {
            get {
                return ResourceManager.GetString("TipTermina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip uputa.
        /// </summary>
        public static string TipUputa {
            get {
                return ResourceManager.GetString("TipUputa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukoliko želite da zakazete termin kod drugog lekara pritisnite na dugme Preference.
        /// </summary>
        public static string ToolTipLekar {
            get {
                return ResourceManager.GetString("ToolTipLekar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukoliko zelite da pomerite ili otkazete termin.
        /// </summary>
        public static string ToolTipModifikacija {
            get {
                return ResourceManager.GetString("ToolTipModifikacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukoliko želite da zakazete termin kod drugog lekara ili da Vam sistem predlozi 3 slobodna termina.
        /// </summary>
        public static string ToolTipPreferenca {
            get {
                return ResourceManager.GetString("ToolTipPreferenca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretražite listu termina po datumu.
        /// </summary>
        public static string ToolTipPretragaDatuma {
            get {
                return ResourceManager.GetString("ToolTipPretragaDatuma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukoliko zakazujete specijalisticki pregled, izaberite uput.
        /// </summary>
        public static string ToolTipUput {
            get {
                return ResourceManager.GetString("ToolTipUput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Kako biste ocenili higijenu radnog mesta lekara?.
        /// </summary>
        public static string Trece {
            get {
                return ResourceManager.GetString("Trece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Kako biste ocenili odnos cena i usluga u Zdravo korporaciji?.
        /// </summary>
        public static string Tri {
            get {
                return ResourceManager.GetString("Tri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neodređeno.
        /// </summary>
        public static string Udovac {
            get {
                return ResourceManager.GetString("Udovac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da zelite da otkazete odabrani termin?.
        /// </summary>
        public static string UpitZaBrisanje {
            get {
                return ResourceManager.GetString("UpitZaBrisanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uvid u selektovano obaveštenje.
        /// </summary>
        public static string UvidObavestenje {
            get {
                return ResourceManager.GetString("UvidObavestenje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uvid u zakazane termine.
        /// </summary>
        public static string UvidUZakazaneTermine {
            get {
                return ResourceManager.GetString("UvidUZakazaneTermine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdravo korporacija je privatni zdravstveni sistem koji nudi najviši kvalitet usluge, 
        ///                    najefikasniji oporavak zdravlja i podstiče na zdrav život svakog pacijenta.
        ///                    Registujte se u najbližem kliničkom centru i iskoristite mogućnosti koje Vam nudi Zdravo korporacija..
        /// </summary>
        public static string Uvod {
            get {
                return ResourceManager.GetString("Uvod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popunite polje.
        /// </summary>
        public static string valAdresa {
            get {
                return ResourceManager.GetString("valAdresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite broj kartice.
        /// </summary>
        public static string valBrojKartice {
            get {
                return ResourceManager.GetString("valBrojKartice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite broj sa zadnje strane kartice.
        /// </summary>
        public static string valCVV {
            get {
                return ResourceManager.GetString("valCVV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite datum.
        /// </summary>
        public static string valDatum {
            get {
                return ResourceManager.GetString("valDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite datum vazenja kartice.
        /// </summary>
        public static string valDatumVazenja {
            get {
                return ResourceManager.GetString("valDatumVazenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite drzavu.
        /// </summary>
        public static string valDrzava {
            get {
                return ResourceManager.GetString("valDrzava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite grad.
        /// </summary>
        public static string valGrad {
            get {
                return ResourceManager.GetString("valGrad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ime.
        /// </summary>
        public static string valIme {
            get {
                return ResourceManager.GetString("valIme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ime i prezime sa kartice.
        /// </summary>
        public static string valImePrezime {
            get {
                return ResourceManager.GetString("valImePrezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dozvoljene su samo cifre.
        /// </summary>
        public static string valJmbg {
            get {
                return ResourceManager.GetString("valJmbg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duzina mora biti od 9 do 13 cifara.
        /// </summary>
        public static string valJmbgDuzina {
            get {
                return ResourceManager.GetString("valJmbgDuzina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite nacin placanja.
        /// </summary>
        public static string valKartica {
            get {
                return ResourceManager.GetString("valKartica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite postanski broj.
        /// </summary>
        public static string valPostanskiBroj {
            get {
                return ResourceManager.GetString("valPostanskiBroj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite prezime.
        /// </summary>
        public static string valPrezime {
            get {
                return ResourceManager.GetString("valPrezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite sadržaj obaveštenja.
        /// </summary>
        public static string valSadrzaj {
            get {
                return ResourceManager.GetString("valSadrzaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uneti vreme u formatu HH:mm.
        /// </summary>
        public static string valVreme {
            get {
                return ResourceManager.GetString("valVreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vreme.
        /// </summary>
        public static string Vreme {
            get {
                return ResourceManager.GetString("Vreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vreme kraja.
        /// </summary>
        public static string VremeKraja {
            get {
                return ResourceManager.GetString("VremeKraja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vreme početka.
        /// </summary>
        public static string VremePocetka {
            get {
                return ResourceManager.GetString("VremePocetka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakaži termin.
        /// </summary>
        public static string ZakaziTermin {
            get {
                return ResourceManager.GetString("ZakaziTermin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zanimanje.
        /// </summary>
        public static string Zanimanje {
            get {
                return ResourceManager.GetString("Zanimanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ženski.
        /// </summary>
        public static string Zenski {
            get {
                return ResourceManager.GetString("Zenski", resourceCulture);
            }
        }
    }
}
