//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projekat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string Datum {
            get {
                return ResourceManager.GetString("Datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum izdavanja uputa.
        /// </summary>
        internal static string DatumIzdavanjaUputa {
            get {
                return ResourceManager.GetString("DatumIzdavanjaUputa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj podsetnik.
        /// </summary>
        internal static string DodajPodsetnik {
            get {
                return ResourceManager.GetString("DodajPodsetnik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronađite lekara po prezimenu, imenu ili specijalizaciji.
        /// </summary>
        internal static string FilterLekari {
            get {
                return ResourceManager.GetString("FilterLekari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specijalistički pregled.
        /// </summary>
        internal static string GboxSpecijalistickiPregled {
            get {
                return ResourceManager.GetString("GboxSpecijalistickiPregled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string Ime {
            get {
                return ResourceManager.GetString("Ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime pacijenta.
        /// </summary>
        internal static string ImePacijenta {
            get {
                return ResourceManager.GetString("ImePacijenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *2. Izaberite datum.
        /// </summary>
        internal static string IzaberiteDatum {
            get {
                return ResourceManager.GetString("IzaberiteDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promeni jezik.
        /// </summary>
        internal static string IzaberiteJezik {
            get {
                return ResourceManager.GetString("IzaberiteJezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *4. Izaberite lekara.
        /// </summary>
        internal static string IzaberiteLekara {
            get {
                return ResourceManager.GetString("IzaberiteLekara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *1. Izaberite tip termina.
        /// </summary>
        internal static string IzaberiteTipTermina {
            get {
                return ResourceManager.GetString("IzaberiteTipTermina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *3. Izaberite vreme početka.
        /// </summary>
        internal static string IzaberiteVremePocetka {
            get {
                return ResourceManager.GetString("IzaberiteVremePocetka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promeni temu.
        /// </summary>
        internal static string IzberiteTemu {
            get {
                return ResourceManager.GetString("IzberiteTemu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG pacijenta.
        /// </summary>
        internal static string JmbgPacijenta {
            get {
                return ResourceManager.GetString("JmbgPacijenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdravstveni karton.
        /// </summary>
        internal static string Karton {
            get {
                return ResourceManager.GetString("Karton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekar kod kog se upućuje.
        /// </summary>
        internal static string LekarKodKogSeUpucuje {
            get {
                return ResourceManager.GetString("LekarKodKogSeUpucuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekar.
        /// </summary>
        internal static string LekarPodaci {
            get {
                return ResourceManager.GetString("LekarPodaci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime i prezime izabranog lekara.
        /// </summary>
        internal static string LekarToolTip {
            get {
                return ResourceManager.GetString("LekarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napomena.
        /// </summary>
        internal static string Napomena {
            get {
                return ResourceManager.GetString("Napomena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekarski uput za specijalistički pregled.
        /// </summary>
        internal static string NaslovUputa {
            get {
                return ResourceManager.GetString("NaslovUputa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔔 Obaveštenja.
        /// </summary>
        internal static string Obavestenja {
            get {
                return ResourceManager.GetString("Obavestenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrisi selektovano obavestenje.
        /// </summary>
        internal static string ObrisiObavestenje {
            get {
                return ResourceManager.GetString("ObrisiObavestenje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjavi se.
        /// </summary>
        internal static string Odjava {
            get {
                return ResourceManager.GetString("Odjava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        internal static string Odustani {
            get {
                return ResourceManager.GetString("Odustani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijent.
        /// </summary>
        internal static string PacijentPodaci {
            get {
                return ResourceManager.GetString("PacijentPodaci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početna stranica.
        /// </summary>
        internal static string Pocetna {
            get {
                return ResourceManager.GetString("Pocetna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomeri.
        /// </summary>
        internal static string Pomeri {
            get {
                return ResourceManager.GetString("Pomeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popuni anketu.
        /// </summary>
        internal static string PopuniAnketu {
            get {
                return ResourceManager.GetString("PopuniAnketu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potpis.
        /// </summary>
        internal static string PotpisLekara {
            get {
                return ResourceManager.GetString("PotpisLekara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled.
        /// </summary>
        internal static string Pregled {
            get {
                return ResourceManager.GetString("Pregled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        internal static string Prezime {
            get {
                return ResourceManager.GetString("Prezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime pacijenta.
        /// </summary>
        internal static string PrezimePacijenta {
            get {
                return ResourceManager.GetString("PrezimePacijenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaš profil.
        /// </summary>
        internal static string Profil {
            get {
                return ResourceManager.GetString("Profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadržaj.
        /// </summary>
        internal static string SadrzajObavestenja {
            get {
                return ResourceManager.GetString("SadrzajObavestenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specijalizacija.
        /// </summary>
        internal static string Specijalizacija {
            get {
                return ResourceManager.GetString("Specijalizacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svetla.
        /// </summary>
        internal static string Svetla {
            get {
                return ResourceManager.GetString("Svetla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamna.
        /// </summary>
        internal static string Tamna {
            get {
                return ResourceManager.GetString("Tamna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        internal static string TipObavestenja {
            get {
                return ResourceManager.GetString("TipObavestenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uvid u selektovano obavestenje.
        /// </summary>
        internal static string UvidObavestenje {
            get {
                return ResourceManager.GetString("UvidObavestenje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uvid u zakazane termine.
        /// </summary>
        internal static string UvidUZakazaneTermine {
            get {
                return ResourceManager.GetString("UvidUZakazaneTermine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakaži termin.
        /// </summary>
        internal static string ZakaziTermin {
            get {
                return ResourceManager.GetString("ZakaziTermin", resourceCulture);
            }
        }
    }
}
